name: 'CI'

on: 
  push: 
    branches: 
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: List directory
      run: |
        ls -la

    - name: List directory
      run: |
        touch new_file.txt    

    